# Site settings
title: Front-ender's notes
description: A front-end developers blog and not only
baseurl: ""
url: "http://vermilion1.github.io"
twitter_username: vpetrychuk
github_username:  vermilion1

# Build settings
markdown: kramdown
paginate: 1
